version: '3.9'

volumes:
  dbdata:

networks:
  geodjango:
    driver: bridge

services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/site
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: geodjango_backend
    depends_on:
      - db
    networks:
      - geodjango

  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: geodjango_db
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - geodjango
